files: "^index.html$"
repos:
  - repo: git@bbgithub.dev.bloomberg.com:pre-commit/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args: ["--write-changes", "--ignore-words-list", "Ned,"]
  - repo: git@bbgithub.dev.bloomberg.com:pre-commit/mirrors-prettier.git
    rev: "v3.1.0"
    hooks:
      - id: prettier
        additional_dependencies:
          - "prettier@3.2.4"
          - "@prettier/plugin-xml@3.2.2"
        args: ["--print-width=120", "--prose-wrap=always"]
